### ISSUE TITLE
[Bug]: jelly teleports when it has been just transformed by an item crystal

### ISSUE THREAD

**Issue by poorlydrawncactus** [CommunalHelper/IsaGrabBag#14]
### Before You Report

- [X] My mods and Everest install are up to date.
- [X] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

mac

### Bug Description

I don't even know how to describe this, but i transofrmed a item crystal with a jelly in it, grabbed the jelly, and when I tried to throw it it warped to above the item crystal pedestal.
![Uploading Untitled_video_-_Made_with_Clipchamp.gif…]()

### Steps to Reproduce

1) transform an item crystal into a jelly
2) throw it

(note: this isn't 100% conisstent - i dont know how to replicate it perfectly)

**Comment by bigkahuna443** [comment]
Did you mean to send this to [Cherry Helper](https://github.com/CommunalHelper/CherryHelper)? It looks like the GIF upload didn't go through either. Could you remake the issue on the correct helper? Thanks!
