### ISSUE TITLE
[Bug]: Door Fields do not properly reset cassette music

### ISSUE THREAD

**Issue by Nataly171** [CommunalHelper/IsaGrabBag#17]
### Before You Report

- [X] My mods and Everest install are up to date.
- [x] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Windows 10

### Bug Description

When entering a Door Field (Room Teleport) in a cassette room which teleports you to a non-cassette room, the cassette room music continues playing until you move into a non-cassette room regularly.

### Steps to Reproduce

Create a map with two rooms. In Room A, just place a spawn point. In Room B, place a spawn point, two cassette blocks to trigger the cassette music, and a Door Field which teleports the player to Room A. Walking between Room A and Room B will change the music as expected. But if you use the Door Field to teleport to Room A, the cassette music continues to play.

**Comment by bigkahuna443** [comment]
Thanks for the report! PR is [here](https://github.com/CommunalHelper/CherryHelper/pull/6).
