### ISSUE TITLE
[Bug]: Shadow Dash endShadowDash isn't properly removed

### ISSUE THREAD

**Issue by viddie** [CommunalHelper/IsaGrabBag#18]
### Before You Report

- [X] My mods and Everest install are up to date.
- [X] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Core

### Bug Description

From what me and my stream chat could gather, its because of this line:

https://github.com/aridai-shi/CherryHelper/blob/d9734704de6308652b7548543416d4a4e4680235/Code/Entities/ShadowDashRefill.cs#L215C17-L215C55

The order of operations that I think is happening here:
- 1st shadow dash has ended, attaches `ShadowEndDelay` coroutine to Player
- 3f later
- 2nd shadow dash is started, sets `CherryHelper.Session.ShadowDashActive = true`
- 2nd shadow dash tries to remove the `ShadowEndDelay` coroutine, but the removal can only take place at the end of the frame
- 1st shadow dash's `ShadowEndDelay` coroutine runs and sets `CherryHelper.Session.ShadowDashActive = false`
- At the end of the frame, the coroutine is removed, but it doesn't matter anymore because it already ran

### Steps to Reproduce

Setup:
- Have a shadow dash and dash into another shadow dash refill
- Dash exactly 3 frames after the first shadow dash ends (the frame that you have 22.5 downwards speed if the first dash was horizontal and you start falling after the dash ends)
- You will not gain invincibility and die to stuff
- If you want to see me figuring this out on stream look here https://www.twitch.tv/videos/2087110397?t=0h52m51s i was so stumped lmao

**Comment by bigkahuna443** [comment]
Thanks for the report! I probably would not have attempted this without the steps you took to reproduce lol. PR is [here](https://github.com/CommunalHelper/CherryHelper/pull/7).
