### ISSUE TITLE
BingoUI Compatibility Issue

### ISSUE THREAD

**Issue by Tiyo98** [CommunalHelper/IsaGrabBag#3]
When using BingoUI and having IsaGrabBag enabled, if you have the "Hide Variants except Grabless" option enabled in BingoUI, enabling the grabless variant and then leaving the current chapter and entering another one disables grabless and enables mirror mode

**Comment by bigkahuna443** [comment]
Fixed by https://github.com/CommunalHelper/IsaGrabBag/commit/d50e7368574b49816ebe3e6de11dfd05b4d522fd and is live in 1.6.8.
