### ISSUE TITLE
waterBoost persistence 

### ISSUE THREAD

**Issue by Kataiser** [CommunalHelper/IsaGrabBag#8]
The waterBoost entity can persist to other maps when loading directly into them from a map that uses it. This can cause its effect to persist into maps it when it shouldn't. This doesn't seem to happen when exiting normally.

"waterboost persists to other maps if you console load, presumably because Level.OnExit isn't invoked and it's stored in a weird meta object instead of the session" -@Kalobi

**Comment by bigkahuna443** [comment]
Fixed in 1.6.11, thanks for reporting!
